version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app
      - /app/node_modules
